SYSMAP = {
    'Atmospheric': 'ATMOSPHERIC',
    'Flowthrough': 'FLOWTHROUGH',
    'Navigation': 'NAVIGATION',
    'Other': 'OTHER',
    'OverTheSide': 'ROSETTE',
    'Sonar': 'SONAR'
}

LOCMAP = {
    'Wet Lab': 'WET-LAB',
    'Tech Stores': 'TECH-STORES',
    'Tech Shop': 'TECH-SHOP',
    'Starboard Side': 'STBD',
    'Science Control Room': 'SCI-CTRL',
    'Port Side': 'PORT',
    'Not Applicable': 'NA',
    'Main Mast': 'MAIN-MAST',
    'Main Lab / Wet Wall': 'MAIN-LAB',
    'Hull':'HULL',
    'Fwd Winch Room': 'WINCH-ROOM',
    'Forward Stores': 'FWD-STORES',
    'Forward Mast': 'FWD-MAST',
    'Computer Lab': 'COMP-LAB',
    'Centerboard': 'CTBD',
    'CTD Winch Room': 'ROSETTE-ROOM',
    'Bow Thruster Room': 'BOW-THRUST',
    'Baltic Room': 'BALTIC-ROOM',
    'Back Deck': 'AFT-DECK',
    'Above SCR': 'SCI-CTRL',
    '03 Lab': 'LAB-03',
    '': 'NA'
}




VARMAP = {
    'sensor_id': 'sensor_id',
    'Sound Velocity': 'speed_of_sound_in_sea_water',
    'Temperature': 'sea_water_temperature',
    'Salinity': 'sea_water_practical_salinity',
    'Conductivity': 'sea_water_electrical_conductivity',
    'Water Depth': 'water_depth',
    'Air Temperature': 'air_temperature',
    'Barometric Pressure': 'barometric_pressure',
    'CO2': 'co2',
    'Cell Temp': 'cell_temperature',
    'Pressure': 'barometric_pressure',
    'Flow': 'water_flow_rate',
    'pCO2': 'pco2',
    'Equil Temp': 'equilibrator_temperature',
    'Coil Temperature': 'coil_temperature',
    'Centerboard Depth': 'centerboard_depth',
    'Oxygen': 'estimated_oxygen_concentration',
    'Air Saturation': 'estimated_oxygen_saturation',
    'Oxygen Corr': 'dissolved_oxygen',
    'RH': 'relative_humidity',
    'Fan Status': 'fan_status',
    'status': 'status',
    'ext_volts': 'main_voltage',
    'Latitude': 'latitude',
    'Longitude': 'longitude',
    'Transducer Offset': 'transducer_offset',
    'Max Range':'max_range',
    'True Wind Dir': 'true_wind_direction',
    'True Wind Spd': 'true_wind_speed',
    'Rel Wind Dir': 'relative_wind_direction',
    'Rel Wind Spd': 'relative_wind_speed',
    'True Wind u': 'true_wind_velocity_u',
    'True Wind v': 'true_wind_velocity_v',
    'Precip Rate': 'precipitation_rate',
    'Precip Accum': 'accumulated_precipitation',
    'Signal Strength': 'signal_strength',
    'Raw 1 Min Avg': 'average_precipitation_rate',
    'Baseline': 'baseline',
    'Wx Code': 'wx_code',
    'Flow Speed': 'flow_rate',
    'Volume Flow': 'flow_volume',
    'COG': 'course_over_ground',
    'SOG': 'speed_over_ground',
    'HDOP': 'horizontal_dilution_of_precision',
    'num_sats': 'satellites_in_view',
    'Geo Point': 'geo_point',
    'Visible Satellites': 'satellites_in_view',
    'GPS Quality': 'gps_quality',
    'Heading': 'heading',
    'Wavelength 3': 'wavelength_3',
    'Wavelength 2': 'wavelength_2',
    'Wavelength 1': 'wavelength_1',
    'Counts 3': 'counts_3',
    'Counts 2': 'counts_2',
    'Counts 1': 'counts_1',
    'Beta650': 'beta_650',
    'Betap650': 'betap_650',
    'bb650': 'bb_650',
    'chl': 'fluorometric_chlorophyll_a',
    'FDOM': 'fluorometric_cdom',
    'bcorr650': 'bcorr_650',
    'bbp650': 'bbp_650',
    'ID': 'source_id',
    'Absorbance(350)':'a350',
    'Absorbance(254)':'a254',
    'ASM':'spectrum_values',
    'Bromide':'bromide_trace',
    'Dark Value':'dark_value',
    'Internal RH': 'internal_relative_humidity',
    'Internal Temperature': 'internal_temperature',
    'Internal Voltage': 'internal_voltage',
    'Lamp On Time': 'lamp_on_time',
    'Lamp Temp': 'lamp_temperature',
    'Lamp Voltage': 'lamp_voltage',
    'Main Current': 'main_current',
    'Main Voltage': 'main_voltage',
    'N in Nitrate': 'nitrogen_in_nitrate',
    'Nitrate Corrected': 'nitrate',
    'Nitrate Uncorrected': 'nitrate_uncorr',
    'Spec Temperature': 'spectrometer_temperature',
    'Instrument Temp': 'instrument_temperature',
    'Diss Gas Press': 'dissolved_gas_pressure',
    'Supply V':'supply_voltage',
    'rad': 'swir',
    'lw_down': 'lwir',
    'body_temp': 'body_temperature',
    'op_mode': 'operation_mode',
    'Skin Temperature': 'sea_surface_skin_temperature',
    'Depth Below Trans': 'depth_below_transducer',
    'Gravity Uncorr': 'gravity_uncorr',
    'Gravity Corrected': 'gravity',
    'Sensor Temp': 'sensor_temperature',
    'Hgt Quality': 'height_quality',
    'Hdg Quality': 'heading_quality',
    'Heave': 'heave',
    'Horiz Quality': 'horizontal_quality',
    'Pitch': 'pitch',
    'Rate of Turn': 'rate_of_turn',
    'Roll': 'roll',
    'Roll and Pitch Qual': 'roll_pitch_quality',
    'net_rad': 'net_radiation',
    'Long Water Speed': 'longitudinal_water_speed',
    'Long Ground Speed': 'longitudinal_ground_speed',
    'Status Ground Speed': 'status_ground_speed',
    'Status Water Speed': 'status_water_speed',
    'Trans Ground Speed': 'transverse_ground_speed',
    'Trans Water Speed': 'transverse_water_speed',

}

